# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod properties
mod_version = 2.0.0-b4
maven_group = com.talhanation
archives_name = smallships
enabled_platforms = fabric

# Minecraft properties
minecraft_version = 1.21.8

# Dependencies
#updated
forge_config_api_port_version = 21.8.1
# maybe update? 3.8.3 was 3.8.1
night_config_version = 3.8.3
# maybe update? 2025.07.20 was 2025.01.05
parchment_version = 2025.07.20
# maybe update? 0.5.0 was 0.4.1
mixinextras_version = 0.5.0

#updated
fabric_loader_version = 0.16.14
#updated
fabric_api_version = 0.133.0+1.21.8
#updated
modmenu_version = 15.0.0

# updated
forge_version = 1.21.8-58.1.0

# maybe 21.8.33
neoforge_version = 21.8.46
