# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod properties
mod_version = 2.0.0-b8
maven_group = com.talhanation
archives_name = smallships
enabled_platforms = fabric,forge,neoforge

# Minecraft properties
minecraft_version = 1.21.8

# Dependencies
forge_config_api_port_version = 21.8.1
night_config_version = 3.8.3
parchment_version = 2025.07.20
mixinextras_version = 0.5.0

fabric_loader_version = 0.16.14
fabric_api_version = 0.133.0+1.21.8
modmenu_version = 15.0.0

forge_version = 1.21.8-58.1.0

neoforge_version = 21.8.46
